/// International dialing codes (E.164) for all countries and common territories.
class CountryCallingCode {
  const CountryCallingCode({
    required this.isoCode,
    required this.nameEn,
    required this.nameZh,
    required this.dialCode,
  });

  final String isoCode;
  final String nameEn;
  final String nameZh;
  final String dialCode;

  String get displayLabel => '$dialCode $nameZh';

  String get searchText =>
      '$dialCode $nameEn $nameZh $isoCode'.toLowerCase();
}

/// Sorted by Chinese name for easier lookup in the app UI.
const List<CountryCallingCode> kCountryCallingCodes = [
  CountryCallingCode(isoCode: 'AL', nameEn: 'Albania', nameZh: '阿尔巴尼亚', dialCode: '+355'),
  CountryCallingCode(isoCode: 'DZ', nameEn: 'Algeria', nameZh: '阿尔及利亚', dialCode: '+213'),
  CountryCallingCode(isoCode: 'AF', nameEn: 'Afghanistan', nameZh: '阿富汗', dialCode: '+93'),
  CountryCallingCode(isoCode: 'AR', nameEn: 'Argentina', nameZh: '阿根廷', dialCode: '+54'),
  CountryCallingCode(isoCode: 'AE', nameEn: 'United Arab Emirates', nameZh: '阿联酋', dialCode: '+971'),
  CountryCallingCode(isoCode: 'AW', nameEn: 'Aruba', nameZh: '阿鲁巴', dialCode: '+297'),
  CountryCallingCode(isoCode: 'OM', nameEn: 'Oman', nameZh: '阿曼', dialCode: '+968'),
  CountryCallingCode(isoCode: 'AZ', nameEn: 'Azerbaijan', nameZh: '阿塞拜疆', dialCode: '+994'),
  CountryCallingCode(isoCode: 'EG', nameEn: 'Egypt', nameZh: '埃及', dialCode: '+20'),
  CountryCallingCode(isoCode: 'ET', nameEn: 'Ethiopia', nameZh: '埃塞俄比亚', dialCode: '+251'),
  CountryCallingCode(isoCode: 'IE', nameEn: 'Ireland', nameZh: '爱尔兰', dialCode: '+353'),
  CountryCallingCode(isoCode: 'EE', nameEn: 'Estonia', nameZh: '爱沙尼亚', dialCode: '+372'),
  CountryCallingCode(isoCode: 'AD', nameEn: 'Andorra', nameZh: '安道尔', dialCode: '+376'),
  CountryCallingCode(isoCode: 'AO', nameEn: 'Angola', nameZh: '安哥拉', dialCode: '+244'),
  CountryCallingCode(isoCode: 'AI', nameEn: 'Anguilla', nameZh: '安圭拉', dialCode: '+1264'),
  CountryCallingCode(isoCode: 'AG', nameEn: 'Antigua and Barbuda', nameZh: '安提瓜和巴布达', dialCode: '+1268'),
  CountryCallingCode(isoCode: 'AT', nameEn: 'Austria', nameZh: '奥地利', dialCode: '+43'),
  CountryCallingCode(isoCode: 'AU', nameEn: 'Australia', nameZh: '澳大利亚', dialCode: '+61'),
  CountryCallingCode(isoCode: 'MO', nameEn: 'Macau', nameZh: '澳门', dialCode: '+853'),
  CountryCallingCode(isoCode: 'BB', nameEn: 'Barbados', nameZh: '巴巴多斯', dialCode: '+1246'),
  CountryCallingCode(isoCode: 'PG', nameEn: 'Papua New Guinea', nameZh: '巴布亚新几内亚', dialCode: '+675'),
  CountryCallingCode(isoCode: 'BS', nameEn: 'Bahamas', nameZh: '巴哈马', dialCode: '+1242'),
  CountryCallingCode(isoCode: 'PK', nameEn: 'Pakistan', nameZh: '巴基斯坦', dialCode: '+92'),
  CountryCallingCode(isoCode: 'PY', nameEn: 'Paraguay', nameZh: '巴拉圭', dialCode: '+595'),
  CountryCallingCode(isoCode: 'PS', nameEn: 'Palestine', nameZh: '巴勒斯坦', dialCode: '+970'),
  CountryCallingCode(isoCode: 'BH', nameEn: 'Bahrain', nameZh: '巴林', dialCode: '+973'),
  CountryCallingCode(isoCode: 'PA', nameEn: 'Panama', nameZh: '巴拿马', dialCode: '+507'),
  CountryCallingCode(isoCode: 'BR', nameEn: 'Brazil', nameZh: '巴西', dialCode: '+55'),
  CountryCallingCode(isoCode: 'BY', nameEn: 'Belarus', nameZh: '白俄罗斯', dialCode: '+375'),
  CountryCallingCode(isoCode: 'BM', nameEn: 'Bermuda', nameZh: '百慕大', dialCode: '+1441'),
  CountryCallingCode(isoCode: 'BG', nameEn: 'Bulgaria', nameZh: '保加利亚', dialCode: '+359'),
  CountryCallingCode(isoCode: 'MP', nameEn: 'Northern Mariana Islands', nameZh: '北马里亚纳群岛', dialCode: '+1670'),
  CountryCallingCode(isoCode: 'BJ', nameEn: 'Benin', nameZh: '贝宁', dialCode: '+229'),
  CountryCallingCode(isoCode: 'BE', nameEn: 'Belgium', nameZh: '比利时', dialCode: '+32'),
  CountryCallingCode(isoCode: 'IS', nameEn: 'Iceland', nameZh: '冰岛', dialCode: '+354'),
  CountryCallingCode(isoCode: 'PR', nameEn: 'Puerto Rico', nameZh: '波多黎各', dialCode: '+1787'),
  CountryCallingCode(isoCode: 'PL', nameEn: 'Poland', nameZh: '波兰', dialCode: '+48'),
  CountryCallingCode(isoCode: 'BA', nameEn: 'Bosnia and Herzegovina', nameZh: '波黑', dialCode: '+387'),
  CountryCallingCode(isoCode: 'BO', nameEn: 'Bolivia', nameZh: '玻利维亚', dialCode: '+591'),
  CountryCallingCode(isoCode: 'BZ', nameEn: 'Belize', nameZh: '伯利兹', dialCode: '+501'),
  CountryCallingCode(isoCode: 'BW', nameEn: 'Botswana', nameZh: '博茨瓦纳', dialCode: '+267'),
  CountryCallingCode(isoCode: 'BT', nameEn: 'Bhutan', nameZh: '不丹', dialCode: '+975'),
  CountryCallingCode(isoCode: 'BF', nameEn: 'Burkina Faso', nameZh: '布基纳法索', dialCode: '+226'),
  CountryCallingCode(isoCode: 'BI', nameEn: 'Burundi', nameZh: '布隆迪', dialCode: '+257'),
  CountryCallingCode(isoCode: 'KP', nameEn: 'North Korea', nameZh: '朝鲜', dialCode: '+850'),
  CountryCallingCode(isoCode: 'GQ', nameEn: 'Equatorial Guinea', nameZh: '赤道几内亚', dialCode: '+240'),
  CountryCallingCode(isoCode: 'DK', nameEn: 'Denmark', nameZh: '丹麦', dialCode: '+45'),
  CountryCallingCode(isoCode: 'DE', nameEn: 'Germany', nameZh: '德国', dialCode: '+49'),
  CountryCallingCode(isoCode: 'TL', nameEn: 'Timor-Leste', nameZh: '东帝汶', dialCode: '+670'),
  CountryCallingCode(isoCode: 'TG', nameEn: 'Togo', nameZh: '多哥', dialCode: '+228'),
  CountryCallingCode(isoCode: 'DO', nameEn: 'Dominican Republic', nameZh: '多米尼加', dialCode: '+1809'),
  CountryCallingCode(isoCode: 'DM', nameEn: 'Dominica', nameZh: '多米尼克', dialCode: '+1767'),
  CountryCallingCode(isoCode: 'RU', nameEn: 'Russia', nameZh: '俄罗斯', dialCode: '+7'),
  CountryCallingCode(isoCode: 'EC', nameEn: 'Ecuador', nameZh: '厄瓜多尔', dialCode: '+593'),
  CountryCallingCode(isoCode: 'ER', nameEn: 'Eritrea', nameZh: '厄立特里亚', dialCode: '+291'),
  CountryCallingCode(isoCode: 'FR', nameEn: 'France', nameZh: '法国', dialCode: '+33'),
  CountryCallingCode(isoCode: 'FO', nameEn: 'Faroe Islands', nameZh: '法罗群岛', dialCode: '+298'),
  CountryCallingCode(isoCode: 'PF', nameEn: 'French Polynesia', nameZh: '法属波利尼西亚', dialCode: '+689'),
  CountryCallingCode(isoCode: 'GF', nameEn: 'French Guiana', nameZh: '法属圭亚那', dialCode: '+594'),
  CountryCallingCode(isoCode: 'PH', nameEn: 'Philippines', nameZh: '菲律宾', dialCode: '+63'),
  CountryCallingCode(isoCode: 'FJ', nameEn: 'Fiji', nameZh: '斐济', dialCode: '+679'),
  CountryCallingCode(isoCode: 'FI', nameEn: 'Finland', nameZh: '芬兰', dialCode: '+358'),
  CountryCallingCode(isoCode: 'CV', nameEn: 'Cape Verde', nameZh: '佛得角', dialCode: '+238'),
  CountryCallingCode(isoCode: 'FK', nameEn: 'Falkland Islands', nameZh: '福克兰群岛', dialCode: '+500'),
  CountryCallingCode(isoCode: 'GM', nameEn: 'Gambia', nameZh: '冈比亚', dialCode: '+220'),
  CountryCallingCode(isoCode: 'CG', nameEn: 'Republic of the Congo', nameZh: '刚果（布）', dialCode: '+242'),
  CountryCallingCode(isoCode: 'CD', nameEn: 'Democratic Republic of the Congo', nameZh: '刚果（金）', dialCode: '+243'),
  CountryCallingCode(isoCode: 'CO', nameEn: 'Colombia', nameZh: '哥伦比亚', dialCode: '+57'),
  CountryCallingCode(isoCode: 'CR', nameEn: 'Costa Rica', nameZh: '哥斯达黎加', dialCode: '+506'),
  CountryCallingCode(isoCode: 'GD', nameEn: 'Grenada', nameZh: '格林纳达', dialCode: '+1473'),
  CountryCallingCode(isoCode: 'GL', nameEn: 'Greenland', nameZh: '格陵兰', dialCode: '+299'),
  CountryCallingCode(isoCode: 'GE', nameEn: 'Georgia', nameZh: '格鲁吉亚', dialCode: '+995'),
  CountryCallingCode(isoCode: 'CU', nameEn: 'Cuba', nameZh: '古巴', dialCode: '+53'),
  CountryCallingCode(isoCode: 'GP', nameEn: 'Guadeloupe', nameZh: '瓜德罗普', dialCode: '+590'),
  CountryCallingCode(isoCode: 'GU', nameEn: 'Guam', nameZh: '关岛', dialCode: '+1671'),
  CountryCallingCode(isoCode: 'GY', nameEn: 'Guyana', nameZh: '圭亚那', dialCode: '+592'),
  CountryCallingCode(isoCode: 'KZ', nameEn: 'Kazakhstan', nameZh: '哈萨克斯坦', dialCode: '+7'),
  CountryCallingCode(isoCode: 'HT', nameEn: 'Haiti', nameZh: '海地', dialCode: '+509'),
  CountryCallingCode(isoCode: 'KR', nameEn: 'South Korea', nameZh: '韩国', dialCode: '+82'),
  CountryCallingCode(isoCode: 'NL', nameEn: 'Netherlands', nameZh: '荷兰', dialCode: '+31'),
  CountryCallingCode(isoCode: 'BQ', nameEn: 'Caribbean Netherlands', nameZh: '荷属加勒比', dialCode: '+599'),
  CountryCallingCode(isoCode: 'ME', nameEn: 'Montenegro', nameZh: '黑山', dialCode: '+382'),
  CountryCallingCode(isoCode: 'HN', nameEn: 'Honduras', nameZh: '洪都拉斯', dialCode: '+504'),
  CountryCallingCode(isoCode: 'KI', nameEn: 'Kiribati', nameZh: '基里巴斯', dialCode: '+686'),
  CountryCallingCode(isoCode: 'DJ', nameEn: 'Djibouti', nameZh: '吉布提', dialCode: '+253'),
  CountryCallingCode(isoCode: 'KG', nameEn: 'Kyrgyzstan', nameZh: '吉尔吉斯斯坦', dialCode: '+996'),
  CountryCallingCode(isoCode: 'GN', nameEn: 'Guinea', nameZh: '几内亚', dialCode: '+224'),
  CountryCallingCode(isoCode: 'GW', nameEn: 'Guinea-Bissau', nameZh: '几内亚比绍', dialCode: '+245'),
  CountryCallingCode(isoCode: 'CA', nameEn: 'Canada', nameZh: '加拿大', dialCode: '+1'),
  CountryCallingCode(isoCode: 'GH', nameEn: 'Ghana', nameZh: '加纳', dialCode: '+233'),
  CountryCallingCode(isoCode: 'GA', nameEn: 'Gabon', nameZh: '加蓬', dialCode: '+241'),
  CountryCallingCode(isoCode: 'KH', nameEn: 'Cambodia', nameZh: '柬埔寨', dialCode: '+855'),
  CountryCallingCode(isoCode: 'CZ', nameEn: 'Czech Republic', nameZh: '捷克', dialCode: '+420'),
  CountryCallingCode(isoCode: 'ZW', nameEn: 'Zimbabwe', nameZh: '津巴布韦', dialCode: '+263'),
  CountryCallingCode(isoCode: 'CM', nameEn: 'Cameroon', nameZh: '喀麦隆', dialCode: '+237'),
  CountryCallingCode(isoCode: 'QA', nameEn: 'Qatar', nameZh: '卡塔尔', dialCode: '+974'),
  CountryCallingCode(isoCode: 'KY', nameEn: 'Cayman Islands', nameZh: '开曼群岛', dialCode: '+1345'),
  CountryCallingCode(isoCode: 'KM', nameEn: 'Comoros', nameZh: '科摩罗', dialCode: '+269'),
  CountryCallingCode(isoCode: 'CI', nameEn: 'Ivory Coast', nameZh: '科特迪瓦', dialCode: '+225'),
  CountryCallingCode(isoCode: 'KW', nameEn: 'Kuwait', nameZh: '科威特', dialCode: '+965'),
  CountryCallingCode(isoCode: 'HR', nameEn: 'Croatia', nameZh: '克罗地亚', dialCode: '+385'),
  CountryCallingCode(isoCode: 'KE', nameEn: 'Kenya', nameZh: '肯尼亚', dialCode: '+254'),
  CountryCallingCode(isoCode: 'CK', nameEn: 'Cook Islands', nameZh: '库克群岛', dialCode: '+682'),
  CountryCallingCode(isoCode: 'CW', nameEn: 'Curacao', nameZh: '库拉索', dialCode: '+599'),
  CountryCallingCode(isoCode: 'LV', nameEn: 'Latvia', nameZh: '拉脱维亚', dialCode: '+371'),
  CountryCallingCode(isoCode: 'LS', nameEn: 'Lesotho', nameZh: '莱索托', dialCode: '+266'),
  CountryCallingCode(isoCode: 'LA', nameEn: 'Laos', nameZh: '老挝', dialCode: '+856'),
  CountryCallingCode(isoCode: 'LB', nameEn: 'Lebanon', nameZh: '黎巴嫩', dialCode: '+961'),
  CountryCallingCode(isoCode: 'LT', nameEn: 'Lithuania', nameZh: '立陶宛', dialCode: '+370'),
  CountryCallingCode(isoCode: 'LR', nameEn: 'Liberia', nameZh: '利比里亚', dialCode: '+231'),
  CountryCallingCode(isoCode: 'LY', nameEn: 'Libya', nameZh: '利比亚', dialCode: '+218'),
  CountryCallingCode(isoCode: 'LI', nameEn: 'Liechtenstein', nameZh: '列支敦士登', dialCode: '+423'),
  CountryCallingCode(isoCode: 'RE', nameEn: 'Reunion', nameZh: '留尼汪', dialCode: '+262'),
  CountryCallingCode(isoCode: 'LU', nameEn: 'Luxembourg', nameZh: '卢森堡', dialCode: '+352'),
  CountryCallingCode(isoCode: 'RW', nameEn: 'Rwanda', nameZh: '卢旺达', dialCode: '+250'),
  CountryCallingCode(isoCode: 'RO', nameEn: 'Romania', nameZh: '罗马尼亚', dialCode: '+40'),
  CountryCallingCode(isoCode: 'MG', nameEn: 'Madagascar', nameZh: '马达加斯加', dialCode: '+261'),
  CountryCallingCode(isoCode: 'MV', nameEn: 'Maldives', nameZh: '马尔代夫', dialCode: '+960'),
  CountryCallingCode(isoCode: 'MT', nameEn: 'Malta', nameZh: '马耳他', dialCode: '+356'),
  CountryCallingCode(isoCode: 'MW', nameEn: 'Malawi', nameZh: '马拉维', dialCode: '+265'),
  CountryCallingCode(isoCode: 'MY', nameEn: 'Malaysia', nameZh: '马来西亚', dialCode: '+60'),
  CountryCallingCode(isoCode: 'ML', nameEn: 'Mali', nameZh: '马里', dialCode: '+223'),
  CountryCallingCode(isoCode: 'MK', nameEn: 'North Macedonia', nameZh: '北马其顿', dialCode: '+389'),
  CountryCallingCode(isoCode: 'MH', nameEn: 'Marshall Islands', nameZh: '马绍尔群岛', dialCode: '+692'),
  CountryCallingCode(isoCode: 'MQ', nameEn: 'Martinique', nameZh: '马提尼克', dialCode: '+596'),
  CountryCallingCode(isoCode: 'YT', nameEn: 'Mayotte', nameZh: '马约特', dialCode: '+262'),
  CountryCallingCode(isoCode: 'MU', nameEn: 'Mauritius', nameZh: '毛里求斯', dialCode: '+230'),
  CountryCallingCode(isoCode: 'MR', nameEn: 'Mauritania', nameZh: '毛里塔尼亚', dialCode: '+222'),
  CountryCallingCode(isoCode: 'US', nameEn: 'United States', nameZh: '美国', dialCode: '+1'),
  CountryCallingCode(isoCode: 'AS', nameEn: 'American Samoa', nameZh: '美属萨摩亚', dialCode: '+1684'),
  CountryCallingCode(isoCode: 'VI', nameEn: 'US Virgin Islands', nameZh: '美属维尔京群岛', dialCode: '+1340'),
  CountryCallingCode(isoCode: 'MN', nameEn: 'Mongolia', nameZh: '蒙古', dialCode: '+976'),
  CountryCallingCode(isoCode: 'MS', nameEn: 'Montserrat', nameZh: '蒙特塞拉特', dialCode: '+1664'),
  CountryCallingCode(isoCode: 'BD', nameEn: 'Bangladesh', nameZh: '孟加拉国', dialCode: '+880'),
  CountryCallingCode(isoCode: 'PE', nameEn: 'Peru', nameZh: '秘鲁', dialCode: '+51'),
  CountryCallingCode(isoCode: 'FM', nameEn: 'Micronesia', nameZh: '密克罗尼西亚', dialCode: '+691'),
  CountryCallingCode(isoCode: 'MM', nameEn: 'Myanmar', nameZh: '缅甸', dialCode: '+95'),
  CountryCallingCode(isoCode: 'MD', nameEn: 'Moldova', nameZh: '摩尔多瓦', dialCode: '+373'),
  CountryCallingCode(isoCode: 'MA', nameEn: 'Morocco', nameZh: '摩洛哥', dialCode: '+212'),
  CountryCallingCode(isoCode: 'MC', nameEn: 'Monaco', nameZh: '摩纳哥', dialCode: '+377'),
  CountryCallingCode(isoCode: 'MZ', nameEn: 'Mozambique', nameZh: '莫桑比克', dialCode: '+258'),
  CountryCallingCode(isoCode: 'MX', nameEn: 'Mexico', nameZh: '墨西哥', dialCode: '+52'),
  CountryCallingCode(isoCode: 'NA', nameEn: 'Namibia', nameZh: '纳米比亚', dialCode: '+264'),
  CountryCallingCode(isoCode: 'ZA', nameEn: 'South Africa', nameZh: '南非', dialCode: '+27'),
  CountryCallingCode(isoCode: 'SS', nameEn: 'South Sudan', nameZh: '南苏丹', dialCode: '+211'),
  CountryCallingCode(isoCode: 'NR', nameEn: 'Nauru', nameZh: '瑙鲁', dialCode: '+674'),
  CountryCallingCode(isoCode: 'NI', nameEn: 'Nicaragua', nameZh: '尼加拉瓜', dialCode: '+505'),
  CountryCallingCode(isoCode: 'NP', nameEn: 'Nepal', nameZh: '尼泊尔', dialCode: '+977'),
  CountryCallingCode(isoCode: 'NE', nameEn: 'Niger', nameZh: '尼日尔', dialCode: '+227'),
  CountryCallingCode(isoCode: 'NG', nameEn: 'Nigeria', nameZh: '尼日利亚', dialCode: '+234'),
  CountryCallingCode(isoCode: 'NU', nameEn: 'Niue', nameZh: '纽埃', dialCode: '+683'),
  CountryCallingCode(isoCode: 'NO', nameEn: 'Norway', nameZh: '挪威', dialCode: '+47'),
  CountryCallingCode(isoCode: 'NF', nameEn: 'Norfolk Island', nameZh: '诺福克岛', dialCode: '+672'),
  CountryCallingCode(isoCode: 'PW', nameEn: 'Palau', nameZh: '帕劳', dialCode: '+680'),
  CountryCallingCode(isoCode: 'PT', nameEn: 'Portugal', nameZh: '葡萄牙', dialCode: '+351'),
  CountryCallingCode(isoCode: 'JP', nameEn: 'Japan', nameZh: '日本', dialCode: '+81'),
  CountryCallingCode(isoCode: 'SE', nameEn: 'Sweden', nameZh: '瑞典', dialCode: '+46'),
  CountryCallingCode(isoCode: 'CH', nameEn: 'Switzerland', nameZh: '瑞士', dialCode: '+41'),
  CountryCallingCode(isoCode: 'SV', nameEn: 'El Salvador', nameZh: '萨尔瓦多', dialCode: '+503'),
  CountryCallingCode(isoCode: 'WS', nameEn: 'Samoa', nameZh: '萨摩亚', dialCode: '+685'),
  CountryCallingCode(isoCode: 'RS', nameEn: 'Serbia', nameZh: '塞尔维亚', dialCode: '+381'),
  CountryCallingCode(isoCode: 'SL', nameEn: 'Sierra Leone', nameZh: '塞拉利昂', dialCode: '+232'),
  CountryCallingCode(isoCode: 'SN', nameEn: 'Senegal', nameZh: '塞内加尔', dialCode: '+221'),
  CountryCallingCode(isoCode: 'CY', nameEn: 'Cyprus', nameZh: '塞浦路斯', dialCode: '+357'),
  CountryCallingCode(isoCode: 'SC', nameEn: 'Seychelles', nameZh: '塞舌尔', dialCode: '+248'),
  CountryCallingCode(isoCode: 'SA', nameEn: 'Saudi Arabia', nameZh: '沙特阿拉伯', dialCode: '+966'),
  CountryCallingCode(isoCode: 'BL', nameEn: 'Saint Barthelemy', nameZh: '圣巴泰勒米', dialCode: '+590'),
  CountryCallingCode(isoCode: 'ST', nameEn: 'Sao Tome and Principe', nameZh: '圣多美和普林西比', dialCode: '+239'),
  CountryCallingCode(isoCode: 'SH', nameEn: 'Saint Helena', nameZh: '圣赫勒拿', dialCode: '+290'),
  CountryCallingCode(isoCode: 'KN', nameEn: 'Saint Kitts and Nevis', nameZh: '圣基茨和尼维斯', dialCode: '+1869'),
  CountryCallingCode(isoCode: 'LC', nameEn: 'Saint Lucia', nameZh: '圣卢西亚', dialCode: '+1758'),
  CountryCallingCode(isoCode: 'MF', nameEn: 'Saint Martin', nameZh: '圣马丁', dialCode: '+590'),
  CountryCallingCode(isoCode: 'SM', nameEn: 'San Marino', nameZh: '圣马力诺', dialCode: '+378'),
  CountryCallingCode(isoCode: 'PM', nameEn: 'Saint Pierre and Miquelon', nameZh: '圣皮埃尔和密克隆', dialCode: '+508'),
  CountryCallingCode(isoCode: 'VC', nameEn: 'Saint Vincent and the Grenadines', nameZh: '圣文森特和格林纳丁斯', dialCode: '+1784'),
  CountryCallingCode(isoCode: 'LK', nameEn: 'Sri Lanka', nameZh: '斯里兰卡', dialCode: '+94'),
  CountryCallingCode(isoCode: 'SK', nameEn: 'Slovakia', nameZh: '斯洛伐克', dialCode: '+421'),
  CountryCallingCode(isoCode: 'SI', nameEn: 'Slovenia', nameZh: '斯洛文尼亚', dialCode: '+386'),
  CountryCallingCode(isoCode: 'SZ', nameEn: 'Eswatini', nameZh: '斯威士兰', dialCode: '+268'),
  CountryCallingCode(isoCode: 'SD', nameEn: 'Sudan', nameZh: '苏丹', dialCode: '+249'),
  CountryCallingCode(isoCode: 'SR', nameEn: 'Suriname', nameZh: '苏里南', dialCode: '+597'),
  CountryCallingCode(isoCode: 'SB', nameEn: 'Solomon Islands', nameZh: '所罗门群岛', dialCode: '+677'),
  CountryCallingCode(isoCode: 'SO', nameEn: 'Somalia', nameZh: '索马里', dialCode: '+252'),
  CountryCallingCode(isoCode: 'TJ', nameEn: 'Tajikistan', nameZh: '塔吉克斯坦', dialCode: '+992'),
  CountryCallingCode(isoCode: 'TW', nameEn: 'Taiwan', nameZh: '台湾', dialCode: '+886'),
  CountryCallingCode(isoCode: 'TH', nameEn: 'Thailand', nameZh: '泰国', dialCode: '+66'),
  CountryCallingCode(isoCode: 'TZ', nameEn: 'Tanzania', nameZh: '坦桑尼亚', dialCode: '+255'),
  CountryCallingCode(isoCode: 'TO', nameEn: 'Tonga', nameZh: '汤加', dialCode: '+676'),
  CountryCallingCode(isoCode: 'TC', nameEn: 'Turks and Caicos Islands', nameZh: '特克斯和凯科斯群岛', dialCode: '+1649'),
  CountryCallingCode(isoCode: 'TT', nameEn: 'Trinidad and Tobago', nameZh: '特立尼达和多巴哥', dialCode: '+1868'),
  CountryCallingCode(isoCode: 'TN', nameEn: 'Tunisia', nameZh: '突尼斯', dialCode: '+216'),
  CountryCallingCode(isoCode: 'TV', nameEn: 'Tuvalu', nameZh: '图瓦卢', dialCode: '+688'),
  CountryCallingCode(isoCode: 'TR', nameEn: 'Turkey', nameZh: '土耳其', dialCode: '+90'),
  CountryCallingCode(isoCode: 'TM', nameEn: 'Turkmenistan', nameZh: '土库曼斯坦', dialCode: '+993'),
  CountryCallingCode(isoCode: 'TK', nameEn: 'Tokelau', nameZh: '托克劳', dialCode: '+690'),
  CountryCallingCode(isoCode: 'WF', nameEn: 'Wallis and Futuna', nameZh: '瓦利斯和富图纳', dialCode: '+681'),
  CountryCallingCode(isoCode: 'VU', nameEn: 'Vanuatu', nameZh: '瓦努阿图', dialCode: '+678'),
  CountryCallingCode(isoCode: 'GT', nameEn: 'Guatemala', nameZh: '危地马拉', dialCode: '+502'),
  CountryCallingCode(isoCode: 'VE', nameEn: 'Venezuela', nameZh: '委内瑞拉', dialCode: '+58'),
  CountryCallingCode(isoCode: 'BN', nameEn: 'Brunei', nameZh: '文莱', dialCode: '+673'),
  CountryCallingCode(isoCode: 'UG', nameEn: 'Uganda', nameZh: '乌干达', dialCode: '+256'),
  CountryCallingCode(isoCode: 'UA', nameEn: 'Ukraine', nameZh: '乌克兰', dialCode: '+380'),
  CountryCallingCode(isoCode: 'UY', nameEn: 'Uruguay', nameZh: '乌拉圭', dialCode: '+598'),
  CountryCallingCode(isoCode: 'UZ', nameEn: 'Uzbekistan', nameZh: '乌兹别克斯坦', dialCode: '+998'),
  CountryCallingCode(isoCode: 'ES', nameEn: 'Spain', nameZh: '西班牙', dialCode: '+34'),
  CountryCallingCode(isoCode: 'GR', nameEn: 'Greece', nameZh: '希腊', dialCode: '+30'),
  CountryCallingCode(isoCode: 'HK', nameEn: 'Hong Kong', nameZh: '香港', dialCode: '+852'),
  CountryCallingCode(isoCode: 'SG', nameEn: 'Singapore', nameZh: '新加坡', dialCode: '+65'),
  CountryCallingCode(isoCode: 'NC', nameEn: 'New Caledonia', nameZh: '新喀里多尼亚', dialCode: '+687'),
  CountryCallingCode(isoCode: 'NZ', nameEn: 'New Zealand', nameZh: '新西兰', dialCode: '+64'),
  CountryCallingCode(isoCode: 'HU', nameEn: 'Hungary', nameZh: '匈牙利', dialCode: '+36'),
  CountryCallingCode(isoCode: 'SY', nameEn: 'Syria', nameZh: '叙利亚', dialCode: '+963'),
  CountryCallingCode(isoCode: 'JM', nameEn: 'Jamaica', nameZh: '牙买加', dialCode: '+1876'),
  CountryCallingCode(isoCode: 'AM', nameEn: 'Armenia', nameZh: '亚美尼亚', dialCode: '+374'),
  CountryCallingCode(isoCode: 'YE', nameEn: 'Yemen', nameZh: '也门', dialCode: '+967'),
  CountryCallingCode(isoCode: 'IQ', nameEn: 'Iraq', nameZh: '伊拉克', dialCode: '+964'),
  CountryCallingCode(isoCode: 'IR', nameEn: 'Iran', nameZh: '伊朗', dialCode: '+98'),
  CountryCallingCode(isoCode: 'IL', nameEn: 'Israel', nameZh: '以色列', dialCode: '+972'),
  CountryCallingCode(isoCode: 'IT', nameEn: 'Italy', nameZh: '意大利', dialCode: '+39'),
  CountryCallingCode(isoCode: 'IN', nameEn: 'India', nameZh: '印度', dialCode: '+91'),
  CountryCallingCode(isoCode: 'ID', nameEn: 'Indonesia', nameZh: '印度尼西亚', dialCode: '+62'),
  CountryCallingCode(isoCode: 'GB', nameEn: 'United Kingdom', nameZh: '英国', dialCode: '+44'),
  CountryCallingCode(isoCode: 'VG', nameEn: 'British Virgin Islands', nameZh: '英属维尔京群岛', dialCode: '+1284'),
  CountryCallingCode(isoCode: 'JO', nameEn: 'Jordan', nameZh: '约旦', dialCode: '+962'),
  CountryCallingCode(isoCode: 'VN', nameEn: 'Vietnam', nameZh: '越南', dialCode: '+84'),
  CountryCallingCode(isoCode: 'ZM', nameEn: 'Zambia', nameZh: '赞比亚', dialCode: '+260'),
  CountryCallingCode(isoCode: 'JE', nameEn: 'Jersey', nameZh: '泽西岛', dialCode: '+44'),
  CountryCallingCode(isoCode: 'TD', nameEn: 'Chad', nameZh: '乍得', dialCode: '+235'),
  CountryCallingCode(isoCode: 'GI', nameEn: 'Gibraltar', nameZh: '直布罗陀', dialCode: '+350'),
  CountryCallingCode(isoCode: 'CL', nameEn: 'Chile', nameZh: '智利', dialCode: '+56'),
  CountryCallingCode(isoCode: 'CF', nameEn: 'Central African Republic', nameZh: '中非', dialCode: '+236'),
  CountryCallingCode(isoCode: 'CN', nameEn: 'China', nameZh: '中国', dialCode: '+86'),
];

/// Preferred ISO codes when multiple countries share the same dial code.
const Map<String, String> _preferredIsoByDialCode = {
  '+1': 'US',
  '+7': 'RU',
  '+44': 'GB',
  '+262': 'RE',
  '+590': 'GP',
  '+599': 'BQ',
};

CountryCallingCode countryCallingCodeForDialCode(String dialCode) {
  final preferredIso = _preferredIsoByDialCode[dialCode];
  if (preferredIso != null) {
    for (final country in kCountryCallingCodes) {
      if (country.isoCode == preferredIso && country.dialCode == dialCode) {
        return country;
      }
    }
  }

  for (final country in kCountryCallingCodes) {
    if (country.dialCode == dialCode) {
      return country;
    }
  }

  return kCountryCallingCodes.firstWhere((country) => country.isoCode == 'CN');
}

List<CountryCallingCode> filterCountryCallingCodes(String query) {
  final normalized = query.trim().toLowerCase();
  if (normalized.isEmpty) {
    return kCountryCallingCodes;
  }

  return kCountryCallingCodes
      .where((country) => country.searchText.contains(normalized))
      .toList(growable: false);
}
